### ISSUE TITLE
Add an export to get SMART Data attributes

### ISSUE THREAD

**Issue by c-michail** [ftyszyx/CrystalDiskInfo_dll_lib#1]
Hello,
  Can you add an export to get the SMART Data attributes ? 
  Also other info such as Power on hours, Firmware etc

Thank you

**Comment by ftyszyx** [comment]
you can add the api export  according to my example and submit the code to this repo by a pull request.
because i only need the disk name and disk searial num ,now.
thank you

**Comment by c-michail** [comment]
The problem is that i'm not a c++ developer. If you find time in the future please consider it.

Thank you

**Comment by c-michail** [comment]
There is also this implementation if it helps: https://github.com/MicaApps/DiskInfo

**Comment by ftyszyx** [comment]
ok,I will take a look,when i have time.

**Comment by c-michail** [comment]
Hello,
  I found that there is already a full supported crystal info dll library so this wont be needed anymore.
  Check: https://github.com/a1ive/libcdi

Thank you
